### ISSUE TITLE
As a Home security system user, I want to be notified when motion is detected by my camera so that I can monitor anomalous activity at my home.

### ISSUE THREAD

**Issue by melippmann** [ChicoState/open-source-security-camera#2]

**Comment by DJ-IRL** [comment]
has been encompassed by another issue in my opinion. @melippmann close if u agree. 

im thinking the email notif might be as far as we go this semester. that would be useful and solve this issue to a meaningful degree.

**Comment by melippmann** [comment]
This issue has been resolved by creating functionality that sends email notifications with video attachments of detected motion.
