### ISSUE TITLE
As a home security camera user, I only want useful footage, such as when people are in the frame or movement is detected, to be stored in order to save time when reviewing, and space on the storage device.

### ISSUE THREAD

**Issue by melippmann** [ChicoState/open-source-security-camera#4]

**Comment by DJ-IRL** [comment]
@melippmann has closed this issue in the form of the `/videos/*` directory which is generated when the code runs. Video is stored in that location when motion is detected and when the camera is running. 

I think it will be a separate issue to get the motion detection dialed in for the various environments, and to make the camera run when the dashboard is not open. 

But as it stands march 29th, we do this when certain conditions are met. 
- dashboard open
- available space on hard drive
