### ISSUE TITLE
Duplicate Login / Join Files

### ISSUE THREAD

**Issue by DJ-IRL** [ChicoState/open-source-security-camera#68]
In some strange twist of fate, we have some duplicate-function files. Specifically our login, join, and other core function files have duplicate templates. 

This is confusing and it is unclear which one is the "working" one. 

**To Reproduce**
1. Go to terminal of your choice
2. Look at our /osCam/templates/ directory
3. Scroll down to core/ and user/ (there are the dups)

**Expected behavior**
A clear and concise layout for templates. We don't need many webpages, so the hierarchy should not be too complex. 

- [x] login
- [x] join
- [x] others

**Comment by Zalymo** [comment]
found no other duplicate files aside from join.html. it seems that login.html and join.html somehow got duplicated into the templates/user folder. everything else in that folder should be there (profile.html, settings.html)
